import { createWriteStream, existsSync } from "node:fs";
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { EmbedBuilder, bold, inlineCode, italic } from "discord.js";
import { upsertNewPlugin, getPluginsByServerId } from "../../lib/db";
import type { Server } from "../../lib/server";
import {
	ensureSuffix,
	removeSuffix,
	safeFetch,
	safeJoin,
	trimTextWithSuffix,
} from "../../lib/utils";
import { downloadAndSave } from "../../lib/utils/web";
import { createPathForPluginFile } from "../../lib/serverInstance/plugin";
import {
	SideValue,
	type ErrorResponse,
	type ListPluginVersionsProps,
	type PluginGetQueryItem,
	type PluginGetVersionItem,
	type PluginListVersionItem,
	type PluginSearchQueryResponse,
	type SearchPluginFacets,
	type SearchPluginProps,
	type CompatResult,
	type FabricVersion,
	type ForgePromotions,
	type MojangManifest,
	type MojangVersionInfo,
} from "./types";

const MODRINTH_API_BASE = "https://api.modrinth.com/v2";

// ─── mcserver constants ───────────────────────────────────────────────────────

export const MOJANG_MANIFEST_URL =
	"https://launchermeta.mojang.com/mc/game/version_manifest_v2.json";
export const FABRIC_META_BASE = "https://meta.fabricmc.net/v2/versions";
export const FORGE_PROMOTIONS_URL =
	"https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json";

// ─── Vanilla helpers ──────────────────────────────────────────────────────────

export async function getMojangReleaseVersions(): Promise<string[]> {
	const res = await fetch(MOJANG_MANIFEST_URL).catch(() => null);
	if (!res?.ok) return [];
	const data = (await res.json()) as MojangManifest;
	return data.versions.filter((v) => v.type === "release").map((v) => v.id);
}

export async function getVanillaServerUrl(
	version: string,
): Promise<string | null> {
	const res = await fetch(MOJANG_MANIFEST_URL).catch(() => null);
	if (!res?.ok) return null;
	const manifest = (await res.json()) as MojangManifest;
	const entry = manifest.versions.find((v) => v.id === version);
	if (!entry) return null;
	const infoRes = await fetch(entry.url).catch(() => null);
	if (!infoRes?.ok) return null;
	const info = (await infoRes.json()) as MojangVersionInfo;
	return info.downloads.server?.url ?? null;
}

// ─── Fabric helpers ───────────────────────────────────────────────────────────

export async function getFabricGameVersions(): Promise<string[]> {
	const res = await fetch(`${FABRIC_META_BASE}/game`).catch(() => null);
	if (!res?.ok) return [];
	const data = (await res.json()) as FabricVersion[];
	return data.filter((v) => v.stable).map((v) => v.version);
}

export async function getLatestStableFabricLoader(): Promise<string | null> {
	const res = await fetch(`${FABRIC_META_BASE}/loader`).catch(() => null);
	if (!res?.ok) return null;
	const data = (await res.json()) as FabricVersion[];
	return data.find((v) => v.stable)?.version ?? null;
}

export async function getLatestStableFabricInstaller(): Promise<string | null> {
	const res = await fetch(`${FABRIC_META_BASE}/installer`).catch(() => null);
	if (!res?.ok) return null;
	const data = (await res.json()) as FabricVersion[];
	return data.find((v) => v.stable)?.version ?? null;
}

export function fabricServerJarUrl(
	mc: string,
	loader: string,
	installer: string,
): string {
	return `${FABRIC_META_BASE}/loader/${mc}/${loader}/${installer}/server/jar`;
}

// ─── Forge helpers ────────────────────────────────────────────────────────────

export async function getForgePromo(
	mcVersion: string,
): Promise<{ recommended: string | null; latest: string | null }> {
	const res = await fetch(FORGE_PROMOTIONS_URL).catch(() => null);
	if (!res?.ok) return { recommended: null, latest: null };
	const data = (await res.json()) as ForgePromotions;
	return {
		recommended: data.promos[`${mcVersion}-recommended`] ?? null,
		latest: data.promos[`${mcVersion}-latest`] ?? null,
	};
}

export function forgeInstallerUrl(
	mcVersion: string,
	forgeVersion: string,
): string {
	return `https://maven.minecraftforge.net/net/minecraftforge/forge/${mcVersion}-${forgeVersion}/forge-${mcVersion}-${forgeVersion}-installer.jar`;
}

// ─── File-system helpers ──────────────────────────────────────────────────────

export async function ensureDir(dir: string) {
	if (!existsSync(dir)) await mkdir(dir, { recursive: true });
}

export async function writeEula(serverDir: string) {
	await writeFile(
		`${serverDir}/eula.txt`,
		`# Generated by ipBotDiscord mcserver command\neula=true\n`,
	);
}

export async function writeStartScript(serverDir: string, jarName: string) {
	await writeFile(
		`${serverDir}/start.sh`,
		`#!/bin/sh\nexec java -Xmx2G -Xms1G -jar ${jarName} nogui\n`,
		{ mode: 0o755 },
	);
}

/** Find JARs in a directory whose name matches a prefix, e.g. "paper-" */
export async function findJarsByPrefix(
	dir: string,
	prefix: string,
): Promise<string[]> {
	if (!existsSync(dir)) return [];
	const files = await readdir(dir);
	return files.filter((f) => f.startsWith(prefix) && f.endsWith(".jar"));
}

/** Run the Forge installer in installServer mode, returns success + output */
export async function runForgeInstaller(
	installerPath: string,
	serverDir: string,
): Promise<{ ok: boolean; output: string }> {
	const proc = Bun.spawn(["java", "-jar", installerPath, "--installServer"], {
		cwd: serverDir,
		stdout: "pipe",
		stderr: "pipe",
	});
	await proc.exited;
	const stdout = await new Response(proc.stdout).text();
	const stderr = await new Response(proc.stderr).text();
	return {
		ok: proc.exitCode === 0,
		output: [stdout, stderr].filter(Boolean).join("\n").slice(0, 1500),
	};
}

// ─── Compatibility check ──────────────────────────────────────────────────────

export async function checkPluginCompatibility(
	serverId: number,
	newMcVersion: string,
	loaderType: string,
): Promise<CompatResult[]> {
	const dbPlugins = await getPluginsByServerId(serverId);
	if (dbPlugins.length === 0) return [];

	const results = await Promise.all(
		dbPlugins.map(async (p): Promise<CompatResult> => {
			const projectInfo = await getPlugin(p.projectId).catch(() => null);
			const title = projectInfo?.title ?? p.projectId;

			const versions = await listPluginVersions(p.projectId, {
				game_versions: [newMcVersion],
				loaders: [loaderType],
			}).catch(() => null);

			if (!versions) {
				return {
					projectId: p.projectId,
					title,
					currentVersion: p.versionId,
					compatible: null,
					availableVersionId: null,
				};
			}

			const newest =
				versions.sort(
					(a, b) => b.date_published - a.date_published,
				)[0] ?? null;

			return {
				projectId: p.projectId,
				title,
				currentVersion: p.versionId,
				compatible: versions.length > 0,
				availableVersionId: newest?.id ?? null,
			};
		}),
	);

	return results;
}

export function buildCompatEmbed(
	results: CompatResult[],
	serverTag: string,
	newVersion: string,
): EmbedBuilder {
	const compatible = results.filter((r) => r.compatible === true);
	const incompatible = results.filter((r) => r.compatible === false);
	const unknown = results.filter((r) => r.compatible === null);

	const formatList = (items: CompatResult[]) =>
		items.length === 0
			? italic("None")
			: items
					.map(
						(r) =>
							`• ${bold(r.title)} (${inlineCode(r.projectId)})`,
					)
					.join("\n");

	const embed = new EmbedBuilder()
		.setTitle(`🔍 Compatibility check — upgrading to ${newVersion}`)
		.setDescription(
			`Server: ${bold(serverTag)}\n\nChecked ${bold(String(results.length))} installed plugin(s)/mod(s) against Minecraft ${bold(newVersion)}.`,
		)
		.setColor(
			incompatible.length > 0
				? 0xe74c3c
				: unknown.length > 0
					? 0xf39c12
					: 0x2ecc71,
		)
		.setTimestamp();

	if (compatible.length > 0) {
		embed.addFields({
			name: `✅ Compatible (${compatible.length})`,
			value: trimTextWithSuffix(formatList(compatible), 1024),
		});
	}
	if (incompatible.length > 0) {
		embed.addFields({
			name: `❌ Incompatible (${incompatible.length})`,
			value: trimTextWithSuffix(formatList(incompatible), 1024),
		});
	}
	if (unknown.length > 0) {
		embed.addFields({
			name: `❓ Unknown / not on Modrinth (${unknown.length})`,
			value: trimTextWithSuffix(formatList(unknown), 1024),
		});
	}

	return embed;
}

function buildFacets(facets?: Partial<SearchPluginFacets>) {
	const result: string[][] = [];
	if (facets?.categories) {
		result.push([...facets.categories.map((v) => `categories:${v}`)]);
	}
	if (facets?.versions) {
		result.push([...facets.versions.map((v) => `versions:${v}`)]);
	}
	if (facets?.project_type) {
		result.push([...facets.project_type.map((v) => `project_type:${v}`)]);
	}

	result.push([
		`server_side:${SideValue.Optional}`,
		`server_side:${SideValue.Required}`,
	]);
	return result;
}

export async function searchPlugins({
	offset = 0,
	query,
	facets,
}: SearchPluginProps) {
	const url = new URL(`${MODRINTH_API_BASE}/search`);
	url.searchParams.set("limit", "100");
	url.searchParams.set("offset", offset.toString());
	url.searchParams.set("facets", JSON.stringify(buildFacets(facets)));

	if (query) {
		url.searchParams.set("query", query);
	}
	const res = await safeFetch(url);
	const data = (await res?.json().catch<ErrorResponse>((err) => ({
		error: "[CLIENT] failed to parse JSON",
		description: err.message,
	}))) as PluginSearchQueryResponse | ErrorResponse;
	return data;
}

export async function getPlugin(slugOrId: string) {
	const url = new URL(`${MODRINTH_API_BASE}/project/${slugOrId}`);
	const res = await safeFetch(url);
	if (!res?.ok) return null;
	const data = (await res.json()) as PluginGetQueryItem;
	return data;
}

export async function getPluginVersionDetails(id: string) {
	const url = new URL(`${MODRINTH_API_BASE}/version/${id}`);
	const res = await safeFetch(url);
	if (!res?.ok) return null;
	const data = (await res.json()) as PluginGetVersionItem;
	return data;
}

export async function listPluginVersions(
	slugOrId: string,
	options?: ListPluginVersionsProps,
) {
	const url = new URL(`${MODRINTH_API_BASE}/project/${slugOrId}/version`);
	if (options?.featured) {
		url.searchParams.set("featured", "true");
	}
	if (options?.loaders) {
		url.searchParams.set("loaders", JSON.stringify(options.loaders));
	}
	if (options?.game_versions) {
		url.searchParams.set(
			"game_versions",
			JSON.stringify(options.game_versions),
		);
	}
	const res = await safeFetch(url);
	if (!res?.ok) return null;
	const data = (await res.json()) as PluginListVersionItem[];
	return data.map(
		(item): PluginListVersionItem<true> => ({
			...item,
			date_published: new Date(item.date_published).getTime(),
		}),
	);
}

export async function downloadPluginFile(
	server: Server,
	id: string,
	force = false,
): Promise<{ filename: string | null; newDownload: boolean }> {
	const metadata = await getPluginVersionDetails(id);
	if (!metadata || !metadata.files[0]) {
		return { filename: null, newDownload: false };
	}
	const filePath = createPathForPluginFile(
		server.config.pluginDir,
		metadata.files[0].filename,
	);
	if (!force && existsSync(filePath)) {
		console.log(
			`File ${metadata.files[0].filename} already exists, skipping download`,
		);
		return { filename: metadata.files[0].filename, newDownload: false };
	}
	const res = await safeFetch(metadata.files[0].url);
	if (!res?.ok) return { filename: null, newDownload: false };
	const stream = createWriteStream(filePath);
	const data = res.body;
	if (!data) return { filename: null, newDownload: false };
	for await (const chunk of data) {
		stream.write(chunk);
	}
	stream.end();
	console.log(`Downloaded ${metadata.files[0].filename}`);
	await upsertNewPlugin({
		create: {
			projectId: metadata.project_id,
			filePath,
			versionId: id,
			serverId: server.id,
		},
		update: { filePath, versionId: id },
		where: {
			projectId_versionId_serverId: {
				versionId: id,
				serverId: server.id,
				projectId: metadata.project_id,
			},
		},
	});
	return { filename: metadata.files[0].filename, newDownload: true };
}

/**
 * Returning the filename of a downloaded plugin, not including custom plugins
 */
export async function getPluginFileName(pluginDir: string, slugOrId: string) {
	const metadata = await getPlugin(slugOrId);
	if (!metadata) return null;
	const versions = (
		await Promise.all(
			metadata.versions.map((v) => getPluginVersionDetails(v)),
		)
	).filter((v) => !!v);
	const versionNames = versions
		.map(
			(v) =>
				v.files[0]?.filename &&
				removeSuffix(v.files[0].filename, ".jar"),
		)
		.filter((v) => !!v);
	const dir = await readdir(pluginDir);
	for (const file of dir) {
		if (versionNames.includes(ensureSuffix(file, ".jar"))) return file;
	}
	return null;
}
