import { createWriteStream, existsSync } from "node:fs";
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { type Entry, fromBuffer } from "yauzl";
import { EmbedBuilder, bold, inlineCode, italic } from "discord.js";
import { upsertNewPlugin, getPluginsByServerId } from "../../lib/db";
import type { Server } from "../../lib/server";
import type { DbPlugin, RichUpdateEntry } from "./types";
import {
	ensureSuffix,
	removeSuffix,
	safeFetch,
	safeJoin,
	trimTextWithSuffix,
} from "../../lib/utils";
import { downloadAndSave } from "../../lib/utils/web";
import { createPathForPluginFile } from "../../lib/serverInstance/plugin";
import {
	SideValue,
	type ErrorResponse,
	type ListPluginVersionsProps,
	type MrpackFile,
	type MrpackIndex,
	type PluginGetQueryItem,
	type PluginGetVersionItem,
	type PluginListVersionItem,
	type PluginSearchQueryResponse,
	type SearchPluginFacets,
	type SearchPluginProps,
	type CompatResult,
	type FabricVersion,
	type ForgePromotions,
	type MojangManifest,
	type MojangVersionInfo,
} from "./types";

const MODRINTH_API_BASE = "https://api.modrinth.com/v2";

// ─── mcserver constants ───────────────────────────────────────────────────────

export const MOJANG_MANIFEST_URL =
	"https://launchermeta.mojang.com/mc/game/version_manifest_v2.json";
export const FABRIC_META_BASE = "https://meta.fabricmc.net/v2/versions";
export const FORGE_PROMOTIONS_URL =
	"https://files.minecraftforge.net/net/minecraftforge/forge/promotions_slim.json";

// ─── Vanilla helpers ──────────────────────────────────────────────────────────

export async function getMojangReleaseVersions(): Promise<string[]> {
	const res = await fetch(MOJANG_MANIFEST_URL).catch(() => null);
	if (!res?.ok) return [];
	const data = (await res.json()) as MojangManifest;
	return data.versions.filter((v) => v.type === "release").map((v) => v.id);
}

export async function getVanillaServerUrl(
	version: string,
): Promise<string | null> {
	const res = await fetch(MOJANG_MANIFEST_URL).catch(() => null);
	if (!res?.ok) return null;
	const manifest = (await res.json()) as MojangManifest;
	const entry = manifest.versions.find((v) => v.id === version);
	if (!entry) return null;
	const infoRes = await fetch(entry.url).catch(() => null);
	if (!infoRes?.ok) return null;
	const info = (await infoRes.json()) as MojangVersionInfo;
	return info.downloads.server?.url ?? null;
}

// ─── Fabric helpers ───────────────────────────────────────────────────────────

export async function getFabricGameVersions(): Promise<string[]> {
	const res = await fetch(`${FABRIC_META_BASE}/game`).catch(() => null);
	if (!res?.ok) return [];
	const data = (await res.json()) as FabricVersion[];
	return data.filter((v) => v.stable).map((v) => v.version);
}

export async function getLatestStableFabricLoader(): Promise<string | null> {
	const res = await fetch(`${FABRIC_META_BASE}/loader`).catch(() => null);
	if (!res?.ok) return null;
	const data = (await res.json()) as FabricVersion[];
	return data.find((v) => v.stable)?.version ?? null;
}

export async function getLatestStableFabricInstaller(): Promise<string | null> {
	const res = await fetch(`${FABRIC_META_BASE}/installer`).catch(() => null);
	if (!res?.ok) return null;
	const data = (await res.json()) as FabricVersion[];
	return data.find((v) => v.stable)?.version ?? null;
}

export function fabricServerJarUrl(
	mc: string,
	loader: string,
	installer: string,
): string {
	return `${FABRIC_META_BASE}/loader/${mc}/${loader}/${installer}/server/jar`;
}

// ─── Forge helpers ────────────────────────────────────────────────────────────

export async function getForgePromo(
	mcVersion: string,
): Promise<{ recommended: string | null; latest: string | null }> {
	const res = await fetch(FORGE_PROMOTIONS_URL).catch(() => null);
	if (!res?.ok) return { recommended: null, latest: null };
	const data = (await res.json()) as ForgePromotions;
	return {
		recommended: data.promos[`${mcVersion}-recommended`] ?? null,
		latest: data.promos[`${mcVersion}-latest`] ?? null,
	};
}

export function forgeInstallerUrl(
	mcVersion: string,
	forgeVersion: string,
): string {
	return `https://maven.minecraftforge.net/net/minecraftforge/forge/${mcVersion}-${forgeVersion}/forge-${mcVersion}-${forgeVersion}-installer.jar`;
}

// ─── File-system helpers ──────────────────────────────────────────────────────

export async function ensureDir(dir: string) {
	if (!existsSync(dir)) await mkdir(dir, { recursive: true });
}

export async function writeEula(serverDir: string) {
	await writeFile(
		`${serverDir}/eula.txt`,
		`# Generated by ipBotDiscord mcserver command\neula=true\n`,
	);
}

export async function writeStartScript(serverDir: string, jarName: string) {
	await writeFile(
		`${serverDir}/start.sh`,
		`#!/bin/sh\nexec java -Xmx8G -Xms1G -jar ${jarName} nogui\n`,
		{ mode: 0o755 },
	);
}

/** Find JARs in a directory whose name matches a prefix, e.g. "paper-" */
export async function findJarsByPrefix(
	dir: string,
	prefix: string,
): Promise<string[]> {
	if (!existsSync(dir)) return [];
	const files = await readdir(dir);
	return files.filter((f) => f.startsWith(prefix) && f.endsWith(".jar"));
}

/** Run the Forge installer in installServer mode, returns success + output */
export async function runForgeInstaller(
	installerPath: string,
	serverDir: string,
): Promise<{ ok: boolean; output: string }> {
	const proc = Bun.spawn(["java", "-jar", installerPath, "--installServer"], {
		cwd: serverDir,
		stdout: "pipe",
		stderr: "pipe",
	});
	await proc.exited;
	const stdout = await new Response(proc.stdout).text();
	const stderr = await new Response(proc.stderr).text();
	return {
		ok: proc.exitCode === 0,
		output: [stdout, stderr].filter(Boolean).join("\n").slice(0, 1500),
	};
}

// ─── Compatibility check ──────────────────────────────────────────────────────

export async function checkPluginCompatibility(
	serverId: number,
	newMcVersion: string,
	loaderType: string,
): Promise<CompatResult[]> {
	const dbPlugins = await getPluginsByServerId(serverId);
	if (dbPlugins.length === 0) return [];

	const results = await Promise.all(
		dbPlugins.map(async (p): Promise<CompatResult> => {
			const projectInfo = await getPlugin(p.projectId).catch(() => null);
			const title = projectInfo?.title ?? p.projectId;

			const versions = await listPluginVersions(p.projectId, {
				game_versions: [newMcVersion],
				loaders: [loaderType],
			}).catch(() => null);

			if (!versions) {
				return {
					projectId: p.projectId,
					title,
					currentVersion: p.versionId,
					compatible: null,
					availableVersionId: null,
				};
			}

			const newest =
				versions.sort(
					(a, b) => b.date_published - a.date_published,
				)[0] ?? null;

			return {
				projectId: p.projectId,
				title,
				currentVersion: p.versionId,
				compatible: versions.length > 0,
				availableVersionId: newest?.id ?? null,
			};
		}),
	);

	return results;
}

/**
 * Check all DB-tracked plugins for this server against Modrinth and return
 * entries where a newer version is available for the server's current
 * Minecraft version + loader.
 */
export async function checkOutdatedPlugins(server: Server): Promise<{
	outdated: RichUpdateEntry[];
	failed: string[];
}> {
	const plugins = await getPluginsByServerId(server.id);
	if (plugins.length === 0) return { outdated: [], failed: [] };

	// Keep only the most-recently updated record per projectId
	const latestByProject = new Map<string, DbPlugin>();
	for (const plugin of plugins) {
		const existing = latestByProject.get(plugin.projectId);
		if (!existing || plugin.updatedAt > existing.updatedAt) {
			latestByProject.set(plugin.projectId, plugin);
		}
	}

	const outdated: RichUpdateEntry[] = [];
	const failed: string[] = [];

	for (const [projectId, plugin] of latestByProject.entries()) {
		const [versions, currentVersionDetails, projectDetails] =
			await Promise.all([
				listPluginVersions(projectId, {
					loaders: [server.config.loaderType],
					game_versions: [server.config.minecraftVersion],
				}),
				getPluginVersionDetails(plugin.versionId),
				getPlugin(projectId),
			]);

		if (!versions || versions.length === 0) {
			failed.push(projectDetails?.title ?? projectId);
			continue;
		}

		const latest = versions[0];
		if (!latest) {
			failed.push(projectDetails?.title ?? projectId);
			continue;
		}

		// Already up-to-date — skip silently
		if (latest.id === plugin.versionId) continue;

		outdated.push({
			plugin,
			projectTitle: projectDetails?.title ?? projectId,
			currentVersionNumber:
				currentVersionDetails?.version_number ?? plugin.versionId,
			currentVersionDate: currentVersionDetails?.date_published
				? new Date(currentVersionDetails.date_published).getTime()
				: null,
			newVersionId: latest.id,
			newVersionNumber: latest.version_number,
			newVersionDate: latest.date_published,
			newFilename: latest.files[0]?.filename ?? "unknown",
			newFileSize: latest.files[0]?.size ?? null,
		});
	}

	return { outdated, failed };
}

/**
 * Build a compact embed summarising outdated plugins found by
 * {@link checkOutdatedPlugins}.  Returns `null` when everything is up-to-date
 * and there is nothing to show.
 */
export function buildOutdatedPluginsEmbed(
	outdated: RichUpdateEntry[],
	failed: string[],
	serverTag: string,
): EmbedBuilder | null {
	if (outdated.length === 0 && failed.length === 0) return null;

	const embed = new EmbedBuilder()
		.setTitle("🔌 Outdated Plugin Check")
		.setColor(outdated.length > 0 ? 0xf39c12 : 0x95a5a6)
		.setDescription(
			outdated.length > 0
				? `${bold(serverTag)} has ${bold(String(outdated.length))} outdated plugin${outdated.length !== 1 ? "s" : ""}. Run ${inlineCode("/updateplugins")} to update.`
				: `${bold(serverTag)} — all tracked plugins are up to date.`,
		)
		.setTimestamp();

	if (outdated.length > 0) {
		const MAX_SHOWN = 10;
		const lines = outdated
			.slice(0, MAX_SHOWN)
			.map(
				(r) =>
					`• ${bold(r.projectTitle)} — ${inlineCode(r.currentVersionNumber)} → ${inlineCode(r.newVersionNumber)}`,
			)
			.join("\n");
		const overflow =
			outdated.length > MAX_SHOWN
				? `\n${italic(`…and ${outdated.length - MAX_SHOWN} more`)}`
				: "";
		embed.addFields({
			name: `⬆️ Updates Available (${outdated.length})`,
			value: trimTextWithSuffix(lines + overflow, 1024),
		});
	}

	if (failed.length > 0) {
		embed.addFields({
			name: `❓ Could Not Check (${failed.length})`,
			value: trimTextWithSuffix(
				failed.map((id) => inlineCode(id)).join(", "),
				1024,
			),
		});
	}

	return embed;
}

export function buildCompatEmbed(
	results: CompatResult[],
	serverTag: string,
	newVersion: string,
): EmbedBuilder {
	const compatible = results.filter((r) => r.compatible === true);
	const incompatible = results.filter((r) => r.compatible === false);
	const unknown = results.filter((r) => r.compatible === null);

	const formatList = (items: CompatResult[]) =>
		items.length === 0
			? italic("None")
			: items
					.map(
						(r) =>
							`• ${bold(r.title)} (${inlineCode(r.projectId)})`,
					)
					.join("\n");

	const embed = new EmbedBuilder()
		.setTitle(`🔍 Compatibility check — upgrading to ${newVersion}`)
		.setDescription(
			`Server: ${bold(serverTag)}\n\nChecked ${bold(String(results.length))} installed plugin(s)/mod(s) against Minecraft ${bold(newVersion)}.`,
		)
		.setColor(
			incompatible.length > 0
				? 0xe74c3c
				: unknown.length > 0
					? 0xf39c12
					: 0x2ecc71,
		)
		.setTimestamp();

	if (compatible.length > 0) {
		embed.addFields({
			name: `✅ Compatible (${compatible.length})`,
			value: trimTextWithSuffix(formatList(compatible), 1024),
		});
	}
	if (incompatible.length > 0) {
		embed.addFields({
			name: `❌ Incompatible (${incompatible.length})`,
			value: trimTextWithSuffix(formatList(incompatible), 1024),
		});
	}
	if (unknown.length > 0) {
		embed.addFields({
			name: `❓ Unknown / not on Modrinth (${unknown.length})`,
			value: trimTextWithSuffix(formatList(unknown), 1024),
		});
	}

	return embed;
}

function buildFacets(
	facets?: Partial<SearchPluginFacets>,
	skipServerSideFilter = false,
) {
	const result: string[][] = [];
	if (facets?.categories) {
		result.push([...facets.categories.map((v) => `categories:${v}`)]);
	}
	if (facets?.versions) {
		result.push([...facets.versions.map((v) => `versions:${v}`)]);
	}
	if (facets?.project_type) {
		result.push([...facets.project_type.map((v) => `project_type:${v}`)]);
	}

	if (!skipServerSideFilter) {
		result.push([
			`server_side:${SideValue.Optional}`,
			`server_side:${SideValue.Required}`,
		]);
	}
	return result;
}

export async function searchPlugins({
	offset = 0,
	query,
	facets,
	skipServerSideFilter = false,
}: SearchPluginProps) {
	const url = new URL(`${MODRINTH_API_BASE}/search`);
	url.searchParams.set("limit", "100");
	url.searchParams.set("offset", offset.toString());
	url.searchParams.set(
		"facets",
		JSON.stringify(buildFacets(facets, skipServerSideFilter)),
	);

	if (query) {
		url.searchParams.set("query", query);
	}
	const res = await safeFetch(url);
	const data = (await res?.json().catch<ErrorResponse>((err) => ({
		error: "[CLIENT] failed to parse JSON",
		description: err.message,
	}))) as PluginSearchQueryResponse | ErrorResponse;
	return data;
}

export async function getPlugin(slugOrId: string) {
	const url = new URL(`${MODRINTH_API_BASE}/project/${slugOrId}`);
	const res = await safeFetch(url);
	if (!res?.ok) return null;
	const data = (await res.json()) as PluginGetQueryItem;
	return data;
}

/**
 * Fetch multiple projects in a single Modrinth API call.
 * Returns a map of projectId → project data for easy lookup.
 * Any IDs that Modrinth can't resolve are silently omitted.
 */
export async function getProjects(
	ids: string[],
): Promise<Map<string, PluginGetQueryItem>> {
	if (ids.length === 0) return new Map();
	const url = new URL(`${MODRINTH_API_BASE}/projects`);
	url.searchParams.set("ids", JSON.stringify(ids));
	const res = await safeFetch(url);
	if (!res?.ok) return new Map();
	const data = (await res.json()) as PluginGetQueryItem[];
	return new Map(data.map((p) => [p.id, p]));
}

/**
 * Fetch multiple versions in a single Modrinth API call.
 * Returns a map of versionId → version data for easy lookup.
 * Synthetic IDs (e.g. "sha1:…" or "mrpack:…") are filtered out before the
 * request is made and will simply be absent from the returned map.
 */
export async function getVersionsBulk(
	ids: string[],
): Promise<Map<string, PluginGetVersionItem>> {
	const realIds = ids.filter(
		(id) => !id.startsWith("sha1:") && !id.startsWith("mrpack:"),
	);
	if (realIds.length === 0) return new Map();
	const url = new URL(`${MODRINTH_API_BASE}/versions`);
	url.searchParams.set("ids", JSON.stringify(realIds));
	const res = await safeFetch(url);
	if (!res?.ok) return new Map();
	const data = (await res.json()) as PluginGetVersionItem[];
	return new Map(data.map((v) => [v.id, v]));
}

export async function getPluginVersionDetails(id: string) {
	const url = new URL(`${MODRINTH_API_BASE}/version/${id}`);
	const res = await safeFetch(url);
	if (!res?.ok) return null;
	const data = (await res.json()) as PluginGetVersionItem;
	return data;
}

export async function listPluginVersions(
	slugOrId: string,
	options?: ListPluginVersionsProps,
) {
	const url = new URL(`${MODRINTH_API_BASE}/project/${slugOrId}/version`);
	if (options?.featured) {
		url.searchParams.set("featured", "true");
	}
	if (options?.loaders) {
		url.searchParams.set("loaders", JSON.stringify(options.loaders));
	}
	if (options?.game_versions) {
		url.searchParams.set(
			"game_versions",
			JSON.stringify(options.game_versions),
		);
	}
	const res = await safeFetch(url);
	if (!res?.ok) return null;
	const data = (await res.json()) as PluginListVersionItem[];
	return data.map(
		(item): PluginListVersionItem<true> => ({
			...item,
			date_published: new Date(item.date_published).getTime(),
		}),
	);
}

export async function downloadPluginFile(
	server: Server,
	id: string,
	force = false,
): Promise<{ filename: string | null; newDownload: boolean }> {
	const metadata = await getPluginVersionDetails(id);
	if (!metadata || !metadata.files[0]) {
		return { filename: null, newDownload: false };
	}
	const filePath = createPathForPluginFile(
		server.config.pluginDir,
		metadata.files[0].filename,
	);
	if (!force && existsSync(filePath)) {
		console.log(
			`File ${metadata.files[0].filename} already exists, skipping download`,
		);
		return { filename: metadata.files[0].filename, newDownload: false };
	}
	const res = await safeFetch(metadata.files[0].url);
	if (!res?.ok) return { filename: null, newDownload: false };
	const stream = createWriteStream(filePath);
	const data = res.body;
	if (!data) return { filename: null, newDownload: false };
	for await (const chunk of data) {
		stream.write(chunk);
	}
	stream.end();
	console.log(`Downloaded ${metadata.files[0].filename}`);
	await upsertNewPlugin({
		create: {
			projectId: metadata.project_id,
			filePath,
			versionId: id,
			serverId: server.id,
		},
		update: { filePath, versionId: id },
		where: {
			projectId_versionId_serverId: {
				versionId: id,
				serverId: server.id,
				projectId: metadata.project_id,
			},
		},
	});
	return { filename: metadata.files[0].filename, newDownload: true };
}

// ─── Modpack helpers ──────────────────────────────────────────────────────────

/**
 * Reads `modrinth.index.json` from a .mrpack buffer.
 */
async function parseMrpackIndex(buffer: Buffer): Promise<MrpackIndex | null> {
	return new Promise((resolve) => {
		fromBuffer(buffer, { lazyEntries: true }, (err, zipFile) => {
			if (err) return resolve(null);
			zipFile.readEntry();
			zipFile.on("entry", (entry: Entry) => {
				if (entry.fileName === "modrinth.index.json") {
					zipFile.openReadStream(entry, (err, readStream) => {
						if (err) return resolve(null);
						const chunks: Buffer[] = [];
						readStream.on("data", (chunk: Buffer) =>
							chunks.push(chunk),
						);
						readStream.on("end", () => {
							try {
								resolve(
									JSON.parse(
										Buffer.concat(chunks).toString("utf-8"),
									) as MrpackIndex,
								);
							} catch {
								resolve(null);
							}
							zipFile.close();
						});
						readStream.on("error", () => resolve(null));
					});
				} else {
					zipFile.readEntry();
				}
			});
			zipFile.on("end", () => resolve(null));
		});
	});
}

/**
 * Copies `overrides/` and `server-overrides/` from a .mrpack buffer into
 * `serverDir`, applying them in order (server-overrides win over overrides).
 */
async function extractMrpackOverrides(
	buffer: Buffer,
	serverDir: string,
	overrideDirs: string[],
): Promise<void> {
	// Process each override directory in sequence to honour layer precedence.
	for (const prefix of overrideDirs) {
		await new Promise<void>((resolve) => {
			fromBuffer(buffer, { lazyEntries: true }, (err, zipFile) => {
				if (err) return resolve();
				zipFile.readEntry();
				zipFile.on("entry", async (entry: Entry) => {
					const fullPrefix = `${prefix}/`;
					if (
						!entry.fileName.startsWith(fullPrefix) ||
						entry.fileName.length <= fullPrefix.length
					) {
						return zipFile.readEntry();
					}

					const relativePath = entry.fileName.slice(
						fullPrefix.length,
					);

					// Skip directory entries and unsafe paths
					if (
						relativePath.endsWith("/") ||
						relativePath.includes("..") ||
						/^[A-Za-z]:[\\/]/.test(relativePath) ||
						relativePath.startsWith("/") ||
						relativePath.startsWith("\\")
					) {
						return zipFile.readEntry();
					}

					const destPath = safeJoin(serverDir, relativePath);
					const parentDir = relativePath
						.split("/")
						.slice(0, -1)
						.join("/");
					if (parentDir) {
						await mkdir(safeJoin(serverDir, parentDir), {
							recursive: true,
						}).catch(() => {});
					}

					zipFile.openReadStream(entry, (err, readStream) => {
						if (err) return zipFile.readEntry();
						const stream = createWriteStream(destPath);
						readStream.on("end", () => zipFile.readEntry());
						readStream.on("error", () => zipFile.readEntry());
						readStream.pipe(stream);
					});
				});
				zipFile.on("end", () => resolve());
				zipFile.on("error", () => resolve());
			});
		});
	}
}

/**
 * Extracts Modrinth { projectId, versionId } from a Modrinth CDN URL.
 * CDN pattern: https://cdn.modrinth.com/data/{projectId}/versions/{versionId}/...
 * Falls back to synthetic IDs derived from the file's declared path + SHA1 hash
 * so that even GitHub-hosted or other non-Modrinth files get a stable DB record.
 */
function parseMrpackFileIds(file: MrpackFile): {
	projectId: string;
	versionId: string;
} {
	for (const url of file.downloads) {
		const match = url.match(
			/cdn\.modrinth\.com\/data\/([^/]+)\/versions\/([^/]+)\//,
		);
		if (match?.[1] && match[2])
			return { projectId: match[1], versionId: match[2] };
	}
	// Fallback: use path as a namespaced project key and SHA1 as version key.
	// The "mrpack:" prefix prevents collisions with real Modrinth project IDs.
	return {
		projectId: `mrpack:${file.path}`,
		versionId: `sha1:${file.hashes.sha1}`,
	};
}

export interface DownloadModpackResult {
	success: boolean;
	name: string | null;
	filesDownloaded: number;
	error?: string;
}

/**
 * Downloads and installs a Modrinth modpack version into a server directory.
 *
 * Steps:
 *  1. Fetch the .mrpack file for the given version ID.
 *  2. Parse `modrinth.index.json` to get the file manifest.
 *  3. Download every server-side file to its declared path inside `serverDir`.
 *  4. Apply `overrides/` then `server-overrides/` on top.
 */
export async function downloadModpackFile(
	server: Server,
	versionId: string,
): Promise<DownloadModpackResult> {
	const metadata = await getPluginVersionDetails(versionId);
	if (!metadata?.files[0]) {
		return {
			success: false,
			filesDownloaded: 0,
			name: null,
			error: "Failed to retrieve version metadata.",
		};
	}

	// Prefer the .mrpack primary file, fall back to first file
	const mrpackFileInfo =
		metadata.files.find((f) => f.filename.endsWith(".mrpack")) ??
		metadata.files[0];

	const res = await safeFetch(mrpackFileInfo.url);
	if (!res?.ok || !res.body) {
		return {
			success: false,
			filesDownloaded: 0,
			name: null,
			error: "Failed to download .mrpack archive.",
		};
	}

	// Buffer the whole archive (mrpack files are typically small)
	const chunks: Buffer[] = [];
	const promises: Promise<unknown>[] = [];
	for await (const chunk of res.body) {
		chunks.push(Buffer.from(chunk));
	}
	const buffer = Buffer.concat(chunks);

	const index = await parseMrpackIndex(buffer);
	if (!index) {
		return {
			success: false,
			filesDownloaded: 0,
			name: null,
			error: "Failed to parse modrinth.index.json inside the .mrpack.",
		};
	}

	let filesDownloaded = 0;

	for (const file of index.files) {
		// Skip client-only files
		if (file.env?.server === "unsupported") continue;

		// Reject path traversal attempts
		if (
			file.path.includes("..") ||
			/^[A-Za-z]:[\\/]/.test(file.path) ||
			file.path.startsWith("/") ||
			file.path.startsWith("\\")
		) {
			console.warn(`[modpack] Skipping unsafe path: ${file.path}`);
			continue;
		}

		const destPath = safeJoin(server.config.serverDir, file.path);
		const parentDir = file.path.split("/").slice(0, -1).join("/");
		if (parentDir) {
			await mkdir(safeJoin(server.config.serverDir, parentDir), {
				recursive: true,
			}).catch(() => {});
		}

		let downloaded = false;
		for (const url of file.downloads) {
			const fileRes = await safeFetch(url);
			if (!fileRes?.ok || !fileRes.body) continue;

			const stream = createWriteStream(destPath);
			for await (const chunk of fileRes.body) {
				stream.write(chunk);
			}
			await new Promise<void>((resolve, reject) => {
				stream.end();
				stream.on("finish", resolve);
				stream.on("error", reject);
			}).catch(() => {});

			filesDownloaded++;
			downloaded = true;
			break;
		}

		if (!downloaded) {
			console.warn(`[modpack] Failed to download file: ${file.path}`);
			continue;
		}

		// Persist a DB record so the file appears in getActivePlugins and
		// can be managed (e.g. removed) via the standard plugin commands.
		const { projectId, versionId: fileVersionId } =
			parseMrpackFileIds(file);
		promises.push(
			upsertNewPlugin({
				create: {
					projectId,
					versionId: fileVersionId,
					filePath: destPath,
					serverId: server.id,
				},
				update: { filePath: destPath, versionId: fileVersionId },
				where: {
					projectId_versionId_serverId: {
						projectId,
						versionId: fileVersionId,
						serverId: server.id,
					},
				},
			}).catch((err) => {
				console.warn(
					`[modpack] Failed to upsert DB record for ${file.path}: ${err}`,
				);
			}),
		);
	}

	// Apply overrides in order: generic first, server-specific second
	await extractMrpackOverrides(buffer, server.config.serverDir, [
		"overrides",
		"server-overrides",
	]);
	await Promise.all(promises);

	return { success: true, filesDownloaded, name: index.name };
}

/**
 * Returning the filename of a downloaded plugin, not including custom plugins
 */
export async function getPluginFileName(pluginDir: string, slugOrId: string) {
	const metadata = await getPlugin(slugOrId);
	if (!metadata) return null;
	const versions = (
		await Promise.all(
			metadata.versions.map((v) => getPluginVersionDetails(v)),
		)
	).filter((v) => !!v);
	const versionNames = versions
		.map(
			(v) =>
				v.files[0]?.filename &&
				removeSuffix(v.files[0].filename, ".jar"),
		)
		.filter((v) => !!v);
	const dir = await readdir(pluginDir);
	for (const file of dir) {
		if (versionNames.includes(ensureSuffix(file, ".jar"))) return file;
	}
	return null;
}
